title: Violet Nix

description: A page to share some Nix wisdom.
theme: just-the-docs

url: https://AuricViolet.github.io
favicon_ico: "/assets/favicon.ico"
color_scheme: dark

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true

