title: Violet Nix
description: A page to share some Nix wisdom.
theme: just-the-docs

url: https://AuricViolet.github.io
favicon_ico: "/assets/favicon.ico"
color_scheme: dark
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
